# Generated by Django 6.0.4 on 2026-05-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description_alter_task_due_to_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.room'),
        ),
    ]
